SOF 170 - WP distance overflow
flylogix/MissionPlanner pull request #5
Opened 2020-09-01 11:45 UTC by LiamFly

Changed calculation of WP_DIST to use target coordinates, so that it can be be calculated without overflow issues

2020-09-01 14:08 UTC, rob-flylogix requested changes

2020-09-01 14:08 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
> +                    return 0;
return _wpdist * multiplierdist;

2020-09-01 14:08 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
> +                if (lat == 0 && lng == 0 || next_lat == 0)
if (_wpdist <  65535 || lat == 0 && lng == 0 || next_lat ==0)

2020-09-01 14:08 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
> +                    return 0;
i.e. we return the existing method if _wpdist < 65535 or lat or lng == 0 or next_lat == 0

2020-09-01 14:08 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
> +                [GroupText("Position")]
remove extra tab

2020-09-01 14:08 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
remove extra tab indents

2020-09-01 14:08 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
correct spelling of postarget

2020-09-01 14:08 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
> +
remove extra newlines

2020-09-01 14:36 UTC, LiamFly commented on ExtLibs/ArduPilot/CurrentState.cs
> correct spelling of postarget

This is how it was spelt in the original function, but I can correct the rest of it if you want

2020-09-01 14:38 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
yes please - I've been tidying up as I find things like this

2020-09-02 08:41 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
> +                    return _wpdist * multiplierdist;
I think we should add "&& next_lng == 0" to next_lat check:

if (_wpdist < 65535 || lat == 0 && lng == 0 || next_lat == 0 && next_lng == 0)

2020-09-02 08:41 UTC, rob-flylogix commented on ExtLibs/ArduPilot/CurrentState.cs
>                      tobMinutes -= 60;
Remove commented out line ?

2020-09-02 08:45 UTC, rob-flylogix requested changes
A couple of small things

2020-09-02 09:02 UTC, rob-flylogix approved these changes

2020-09-02 10:09 UTC, closed without merging